// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXozgYbMv4o0vTJfiUeq0XwcUY0f0ZWio',
    appId: '1:70782422707:web:49199c03fa7cb37301aac6',
    messagingSenderId: '70782422707',
    projectId: 'night-life-a0e72',
    authDomain: 'night-life-a0e72.firebaseapp.com',
    storageBucket: 'night-life-a0e72.firebasestorage.app',
    measurementId: 'G-R40PLTKJR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB5XEi7ljJ-fmGSA86UPCVxRxqZJb9vKg',
    appId: '1:70782422707:android:c572497e38a39e8401aac6',
    messagingSenderId: '70782422707',
    projectId: 'night-life-a0e72',
    storageBucket: 'night-life-a0e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByX6JFikvM1O9qv8uJ2y2h0mYfCE3gvXU',
    appId: '1:70782422707:ios:0fdc8d3ce51463d401aac6',
    messagingSenderId: '70782422707',
    projectId: 'night-life-a0e72',
    storageBucket: 'night-life-a0e72.firebasestorage.app',
    iosBundleId: 'com.example.nightLife',
  );
}
